### ISSUE TITLE
'uipf -l' generates symbol lookup error on Debian 9.3 / Ubuntu 17.10

### ISSUE THREAD

**Issue by jdkuhnke** [uipf/uipf#2]
Hi,

I want to extend UIPF for my bachelor thesis. Therefore, I compiled UIPF successfully after removing a [circular dependency](https://github.com/jdkuhnke/uipf/commit/517070a26e566339467c64ba16ebef7e834b5065). Unfortunately I encountered an error which I don't seem to be able to fix even after considerable time and effort. Maybe you can help me, @cebe ?

### The problem
The modules are not loaded correctly when executing `uipf -l`. I think it may be a problem with Glibmm or a mistake by me. The concrete error seems to be: `symbol lookup error` resulting in `GModule-CRITICAL **: g_module_name: assertion 'module != NULL' failed`. (see attached logs for more)

### Details
I could pinpoint the error to [`libModule->get_symbol`](https://github.com/uipf/uipf/blob/a944237e71cc61be29c641f7320e8ee3a0f0624f/code/libuipf/src/ModuleLoader.cpp#L281) or [`//UIPF_LOG_TRACE("Found Module: ", libModule->get_name());`](https://github.com/uipf/uipf/blob/a944237e71cc61be29c641f7320e8ee3a0f0624f/code/libuipf/src/ModuleLoader.cpp#L271) (if you uncomment this log trace).

The module is instantiated correctly according to [Glibmm](https://github.com/GNOME/glibmm/blob/master/glib/src/module.hg) as `Glib::Module::bool()` is overriden to check for [success](https://github.com/GNOME/glibmm/blob/8724cfedd70991c8545fe96d5cf6b7f051e69ce1/glib/src/module.hg#L58):
```
if(libModule) {
      // do something; e.g. UIPF_LOG_TRACE("SUCCESS");
      // this (would) get executed
} 
```

### How to reproduce the error:
0. fresh install of Ubuntu 17.10 or Debian 9.3 (I tried both with the same result)
1. `sudo apt-get install libboost-serialization-dev libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev libopencv-dev qtbase5-dev qtbase5-dev-tools libglibmm-2.4-dev build-essential cmake pkg-config clang libcgal-dev libcgal-qt5-dev`
2. install Qt Creator as instructed in the readme
3. build as instructed (use the test branch of [my fork](https://github.com/jdkuhnke/uipf/tree/test) as the master branch here seems to result in circular dependency issue. This may also be a mistake on my part! But it would not compile otherwise because of undefined references. )
4. `sudo ldconfig`
5. `uipf -l`

### System and logs
OS: Ubuntu 17.10 / Debian 9.3
Glibmm: 2.4
Boost: 1.62
* [uipf-l--trace.log](https://github.com/uipf/uipf/files/1794489/uipf-l--trace.log)
* [uipf-l--trace--LD_DEBUG.log](https://github.com/uipf/uipf/files/1794490/uipf-l--trace--LD_DEBUG.log)

The file paths mentioned in the logs do exist (e.g. "/usr/local/lib/uipf/libResizeModule.so").

&nbsp;

I hope I could explain my problem properly and appreciate any help or thoughts on this matter.

Sincerely,
Dominik

**Comment by cebe** [comment]
Hi Dominik,

> use the test branch of my fork as the master branch here seems to result in circular dependency issue.

There seems to be a problem with some test file, which you can ignore if you compile with cmake option `cmake .. -DWITH_TESTS=off`

I tried to run a build in an lxc container using debian 9.3:

```
sudo lxc-create -n uipf-debian93 --template=debian -- -r stretch
sudo lxc-start -n uipf-debian93
sudo lxc-attach -n uipf-debian93
apt-get update
apt-get dist-upgrade
cat /etc/debian_version # this is 9.3 now
apt-get install libboost-serialization-dev libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev libopencv-dev qtbase5-dev qtbase5-dev-tools libglibmm-2.4-dev build-essential cmake pkg-config clang libcgal-dev libcgal-qt5-dev
apt-get install git
```

build

```
git clone https://github.com/uipf/uipf /usr/local/src/uipf
cd /usr/local/src/uipf
mkdir code/build
cd code/build
cmake .. -DWITH_TESTS=off
make
```

after that running `uipf -l` works as expected:

```
# ./uipf -l
uipf.opencv.copy
uipf.opencv.imgproc.resize
uipf.opencv.load
uipf.opencv.load_images
uipf.opencv.store_image
```

Need to figure out whats wrong with the test, but the issue you described seems to be related to your changes as far as I can see.

**Comment by cebe** [comment]
I committed a fix, that should allow you to compile uipf with tests enabled. Tests seem to fail though.

**Comment by cebe** [comment]
:arrow_right: #3

**Comment by jdkuhnke** [comment]
Thanks for you fast reply!

The uipf master branch compiles successfully now (using a fresh debian 9.3 install on VirtualBox). However, I am still receiving the exact same error messages executing `uipf -l` after building according to your commands:

> ~$ ./uipf -l
> 
> (process:1528): GModule-CRITICAL **: g_module_symbol: assertion 'module != NULL' failed
> Error: Failed to load module: /usr/local/lib/uipf/libLoadImageModule.so - 
> 
> (process:1528): GModule-CRITICAL **: g_module_symbol: assertion 'module != NULL' failed
> Error: Failed to load module: /usr/local/lib/uipf/libCopyImageModule.so - 
> 
> (process:1528): GModule-CRITICAL **: g_module_symbol: assertion 'module != NULL' failed
> Error: Failed to load module: /usr/local/lib/uipf/libStoreImageModule.so - 
> 
> (process:1528): GModule-CRITICAL **: g_module_symbol: assertion 'module != NULL' failed
> Error: Failed to load module: /usr/local/lib/uipf/libResizeModule.so - 
> 
> (process:1528): GModule-CRITICAL **: g_module_symbol: assertion 'module != NULL' failed
> Error: Failed to load module: /usr/local/lib/uipf/libLoadImagesModule.so -

**Comment by cebe** [comment]
that is weird, do your build steps differ from mine? If so, how?

**Comment by jdkuhnke** [comment]
I agree that it's weird. I just did it again to be sure and the only difference is the type of virtualization, I think.

All commands I executed after installing debian 9.3 (net install version):
```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install libboost-serialization-dev libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev libopencv-dev qtbase5-dev qtbase5-dev-tools libglibmm-2.4-dev build-essential cmake pkg-config clang libcgal-dev libcgal-qt5-dev
sudo apt-get install git

sudo git clone https://github.com/uipf/uipf /usr/local/src/uipf
cd /usr/local/src/uipf
sudo mkdir code/build
cd code/build
sudo cmake ..
sudo make
sudo make install

sudo ldconfig # has to be called to use the 'uipf -l' command, and not the local file
sudo uipf -l
```

**Comment by cebe** [comment]
I skipped the `make install` part. Will try again with `make install`.

**Comment by cebe** [comment]
```
# make install
# uipf -l
uipf: error while loading shared libraries: libuipf.so.2.0: cannot open shared object file: No such file or directory
# ldconfig 
# uipf -l
uipf.opencv.copy
uipf.opencv.imgproc.resize
uipf.opencv.load
uipf.opencv.load_images
uipf.opencv.store_image
```

works fine.

**Comment by cebe** [comment]
Can you give the output of the following commands?

```
uname -a
cat /etc/debian_version
gcc --version
clang --version
dpkg -l | grep libglib
dpkg -l | grep opencv
```

**Comment by jdkuhnke** [comment]
I used 2 instances of debian (named Debian 2 / Debian3). The differences between these two are in kernel and debian version.

#### Debian 2
```
$ uname -a
Linux dominik 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux


$ cat /etc/debian_version
9.3

$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0.20170516

$ clang --version
clang version 3.8.1-24 (tag/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstallerDir: /usr/bin

$ dpkg -l | grep libglib
ii  libglib-perl                           3:1.324-1                                   amd64        interface to the GLib and GObject libraries
ii  libglib2.0-0:amd64                     2.50.3-2                                    amd64        GLib library of C routines
ii  libglib2.0-bin                         2.50.3-2                                    amd64        Programs for the GLib library
ii  libglib2.0-data                        2.50.3-2                                    all          Common files for GLib library
ii  libglib2.0-dev                         2.50.3-2                                    amd64        Development files for the GLib library
ii  libglibmm-2.4-1v5:amd64                2.50.0-1                                    amd64        C++ wrapper for the GLib toolkit (shared libraries)
ii  libglibmm-2.4-dev:amd64                2.50.0-1                                    amd64        C++ wrapper for the GLib toolkit (development files)

$ dpkg -l | grep opencv
ii  libopencv-calib3d-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-calib3d
ii  libopencv-calib3d2.4v5:amd64           2.4.9.1+dfsg1-2                             amd64        computer vision Camera Calibration library
ii  libopencv-contrib-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-contrib
ii  libopencv-contrib2.4v5:amd64           2.4.9.1+dfsg1-2                             amd64        computer vision contrib library
ii  libopencv-core-dev:amd64               2.4.9.1+dfsg1-2                             amd64        development files for libopencv-core
ii  libopencv-core2.4v5:amd64              2.4.9.1+dfsg1-2                             amd64        computer vision core library
ii  libopencv-dev                          2.4.9.1+dfsg1-2                             amd64        development files for opencv
ii  libopencv-features2d-dev:amd64         2.4.9.1+dfsg1-2                             amd64        development files for libopencv-features2d
ii  libopencv-features2d2.4v5:amd64        2.4.9.1+dfsg1-2                             amd64        computer vision Feature Detection and Descriptor Extraction library
ii  libopencv-flann-dev:amd64              2.4.9.1+dfsg1-2                             amd64        development files for libopencv-flann
ii  libopencv-flann2.4v5:amd64             2.4.9.1+dfsg1-2                             amd64        computer vision Clustering and Search in Multi-Dimensional spaces library
ii  libopencv-gpu-dev:amd64                2.4.9.1+dfsg1-2                             amd64        development files for libopencv-gpu2.4v5
ii  libopencv-gpu2.4v5:amd64               2.4.9.1+dfsg1-2                             amd64        computer vision GPU library
ii  libopencv-highgui-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-highgui
ii  libopencv-highgui2.4-deb0:amd64        2.4.9.1+dfsg1-2                             amd64        computer vision High-level GUI and Media I/O library
ii  libopencv-imgproc-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-imgproc
ii  libopencv-imgproc2.4v5:amd64           2.4.9.1+dfsg1-2                             amd64        computer vision Image Processing library
ii  libopencv-legacy-dev:amd64             2.4.9.1+dfsg1-2                             amd64        development files for libopencv-legacy
ii  libopencv-legacy2.4v5:amd64            2.4.9.1+dfsg1-2                             amd64        computer vision legacy library
ii  libopencv-ml-dev:amd64                 2.4.9.1+dfsg1-2                             amd64        development files for libopencv-ml
ii  libopencv-ml2.4v5:amd64                2.4.9.1+dfsg1-2                             amd64        computer vision Machine Learning library
ii  libopencv-objdetect-dev:amd64          2.4.9.1+dfsg1-2                             amd64        development files for libopencv-objdetect
ii  libopencv-objdetect2.4v5:amd64         2.4.9.1+dfsg1-2                             amd64        computer vision Object Detection library
ii  libopencv-ocl-dev:amd64                2.4.9.1+dfsg1-2                             amd64        development files for libopencv-ocl2.4v5
ii  libopencv-ocl2.4v5:amd64               2.4.9.1+dfsg1-2                             amd64        computer vision OpenCL support library
ii  libopencv-photo-dev:amd64              2.4.9.1+dfsg1-2                             amd64        development files for libopencv-photo2.4v5
ii  libopencv-photo2.4v5:amd64             2.4.9.1+dfsg1-2                             amd64        computer vision computational photography library
ii  libopencv-stitching-dev:amd64          2.4.9.1+dfsg1-2                             amd64        development files for libopencv-stitching2.4v5
ii  libopencv-stitching2.4v5:amd64         2.4.9.1+dfsg1-2                             amd64        computer vision image stitching library
ii  libopencv-superres-dev:amd64           2.4.9.1+dfsg1-2                             amd64        development files for libopencv-superres2.4v5
ii  libopencv-superres2.4v5:amd64          2.4.9.1+dfsg1-2                             amd64        computer vision Super Resolution library
ii  libopencv-ts-dev:amd64                 2.4.9.1+dfsg1-2                             amd64        development files for libopencv-ts2.4v5
ii  libopencv-ts2.4v5:amd64                2.4.9.1+dfsg1-2                             amd64        computer vision ts library
ii  libopencv-video-dev:amd64              2.4.9.1+dfsg1-2                             amd64        development files for libopencv-video
ii  libopencv-video2.4v5:amd64             2.4.9.1+dfsg1-2                             amd64        computer vision Video analysis library
ii  libopencv-videostab-dev:amd64          2.4.9.1+dfsg1-2                             amd64        development files for libopencv-videostab2.4v5
ii  libopencv-videostab2.4v5:amd64         2.4.9.1+dfsg1-2                             amd64        computer vision video stabilization library
ii  libopencv2.4-java                      2.4.9.1+dfsg1-2                             all          Java bindings for the computer vision library
ii  libopencv2.4-jni                       2.4.9.1+dfsg1-2                             amd64        Java jni library for the computer vision library
ii  opencv-data                            2.4.9.1+dfsg1-2                             all          development data for opencv
```


#### Debian3
```
$ uname -a
Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86 GNU/Linux

$ cat /etc/debian_version
9.4

$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0.20170516

$ clang --version
clang version 3.8.1-24 (tag/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstallerDir: /usr/bin

$ dpkg -l | grep libglib
ii  libglib-perl                           3:1.324-1                                   amd64        interface to the GLib and GObject libraries
ii  libglib2.0-0:amd64                     2.50.3-2                                    amd64        GLib library of C routines
ii  libglib2.0-bin                         2.50.3-2                                    amd64        Programs for the GLib library
ii  libglib2.0-data                        2.50.3-2                                    all          Common files for GLib library
ii  libglib2.0-dev                         2.50.3-2                                    amd64        Development files for the GLib library
ii  libglibmm-2.4-1v5:amd64                2.50.0-1                                    amd64        C++ wrapper for the GLib toolkit (shared libraries)
ii  libglibmm-2.4-dev:amd64                2.50.0-1                                    amd64        C++ wrapper for the GLib toolkit (development files)

$ dpkg -l | grep opencv
ii  libopencv-calib3d-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-calib3d
ii  libopencv-calib3d2.4v5:amd64           2.4.9.1+dfsg1-2                             amd64        computer vision Camera Calibration library
ii  libopencv-contrib-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-contrib
ii  libopencv-contrib2.4v5:amd64           2.4.9.1+dfsg1-2                             amd64        computer vision contrib library
ii  libopencv-core-dev:amd64               2.4.9.1+dfsg1-2                             amd64        development files for libopencv-core
ii  libopencv-core2.4v5:amd64              2.4.9.1+dfsg1-2                             amd64        computer vision core library
ii  libopencv-dev                          2.4.9.1+dfsg1-2                             amd64        development files for opencv
ii  libopencv-features2d-dev:amd64         2.4.9.1+dfsg1-2                             amd64        development files for libopencv-features2d
ii  libopencv-features2d2.4v5:amd64        2.4.9.1+dfsg1-2                             amd64        computer vision Feature Detection and Descriptor Extraction library
ii  libopencv-flann-dev:amd64              2.4.9.1+dfsg1-2                             amd64        development files for libopencv-flann
ii  libopencv-flann2.4v5:amd64             2.4.9.1+dfsg1-2                             amd64        computer vision Clustering and Search in Multi-Dimensional spaces library
ii  libopencv-gpu-dev:amd64                2.4.9.1+dfsg1-2                             amd64        development files for libopencv-gpu2.4v5
ii  libopencv-gpu2.4v5:amd64               2.4.9.1+dfsg1-2                             amd64        computer vision GPU library
ii  libopencv-highgui-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-highgui
ii  libopencv-highgui2.4-deb0:amd64        2.4.9.1+dfsg1-2                             amd64        computer vision High-level GUI and Media I/O library
ii  libopencv-imgproc-dev:amd64            2.4.9.1+dfsg1-2                             amd64        development files for libopencv-imgproc
ii  libopencv-imgproc2.4v5:amd64           2.4.9.1+dfsg1-2                             amd64        computer vision Image Processing library
ii  libopencv-legacy-dev:amd64             2.4.9.1+dfsg1-2                             amd64        development files for libopencv-legacy
ii  libopencv-legacy2.4v5:amd64            2.4.9.1+dfsg1-2                             amd64        computer vision legacy library
ii  libopencv-ml-dev:amd64                 2.4.9.1+dfsg1-2                             amd64        development files for libopencv-ml
ii  libopencv-ml2.4v5:amd64                2.4.9.1+dfsg1-2                             amd64        computer vision Machine Learning library
ii  libopencv-objdetect-dev:amd64          2.4.9.1+dfsg1-2                             amd64        development files for libopencv-objdetect
ii  libopencv-objdetect2.4v5:amd64         2.4.9.1+dfsg1-2                             amd64        computer vision Object Detection library
ii  libopencv-ocl-dev:amd64                2.4.9.1+dfsg1-2                             amd64        development files for libopencv-ocl2.4v5
ii  libopencv-ocl2.4v5:amd64               2.4.9.1+dfsg1-2                             amd64        computer vision OpenCL support library
ii  libopencv-photo-dev:amd64              2.4.9.1+dfsg1-2                             amd64        development files for libopencv-photo2.4v5
ii  libopencv-photo2.4v5:amd64             2.4.9.1+dfsg1-2                             amd64        computer vision computational photography library
ii  libopencv-stitching-dev:amd64          2.4.9.1+dfsg1-2                             amd64        development files for libopencv-stitching2.4v5
ii  libopencv-stitching2.4v5:amd64         2.4.9.1+dfsg1-2                             amd64        computer vision image stitching library
ii  libopencv-superres-dev:amd64           2.4.9.1+dfsg1-2                             amd64        development files for libopencv-superres2.4v5
ii  libopencv-superres2.4v5:amd64          2.4.9.1+dfsg1-2                             amd64        computer vision Super Resolution library
ii  libopencv-ts-dev:amd64                 2.4.9.1+dfsg1-2                             amd64        development files for libopencv-ts2.4v5
ii  libopencv-ts2.4v5:amd64                2.4.9.1+dfsg1-2                             amd64        computer vision ts library
ii  libopencv-video-dev:amd64              2.4.9.1+dfsg1-2                             amd64        development files for libopencv-video
ii  libopencv-video2.4v5:amd64             2.4.9.1+dfsg1-2                             amd64        computer vision Video analysis library
ii  libopencv-videostab-dev:amd64          2.4.9.1+dfsg1-2                             amd64        development files for libopencv-videostab2.4v5
ii  libopencv-videostab2.4v5:amd64         2.4.9.1+dfsg1-2                             amd64        computer vision video stabilization library
ii  libopencv2.4-java                      2.4.9.1+dfsg1-2                             all          Java bindings for the computer vision library
ii  libopencv2.4-jni                       2.4.9.1+dfsg1-2                             amd64        Java jni library for the computer vision library
ii  opencv-data                            2.4.9.1+dfsg1-2                             all          development data for opencv
```

**Comment by cebe** [comment]
the only thing that differs between our environments is the kernel, but I do not see how a different kernel should influence loading of library symbols...

**Comment by jdkuhnke** [comment]
I just tried again with a live debian from a usb drive to check if my virtualization environment is buggy. (Though the current version now is debian 9.4, same libs as in my previous comment) I am still getting the same errors. Hence, VirtualBox shouldn't be the cause.

**Comment by cebe** [comment]
I'm out of ideas on this one, sorry.

**Comment by cebe** [comment]
does installing the binaries from .deb files work for you? https://github.com/uipf/uipf/releases/tag/2.0.0-alpha

**Comment by jdkuhnke** [comment]
This works fine on a fresh install. So something in my building process should be wrong.
